##
## Config file for CAP client 21.6.1.dev7+g9fa5821
##
##   config options are commented with respective default values
##

##
## fe261_enable: if true, "Login FE216" button visible
##
fe261_enable = true

##
## joule_enable: if true, "Login Joule" button visible
##
# joule_enable = true

##
## watt_enable: if true, "Login Watt" button visible
##
# watt_enable = true

##
## vee_enable: if true, "Login VEE" button visible
##
# vee_enable = false

##
## server_address: override serverAddress (IP of host listening for CAP packets)
##
# server_address = ""

##
## server_port: override serverPort (Port of host listening for CAP packets)
##
# server_port = 62201

##
## external_address: override externalAddress (IP of client)
##
# external_address = ""

