name: Release CAP Client binaries

on:
  push:
    branches: [ main, mwm/ci ]
  release:
    types: [created]

jobs:
  releases-matrix:
    name: Build and Test Go Binaries
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # go-version: [1.17.x]
        # os: [ubuntu-latest, macos-latest, windows-latest]
        goos: [darwin, linux, windows]
        goarch: [amd64]
    steps:

      # - name: Install Go
      #   uses: actions/setup-go@v2
      #   with:
      #     go-version: ${{ matrix.go-version }}

      - name: Checkout code
        uses: actions/checkout@v2

      - name:  Install Dependencies
        shell: bash
        run:   |
              if [ "$RUNNER_OS" == "Linux" ]; then
                    sudo apt install -y libgl1-mesa-dev xorg-dev
              fi

      - name: Test
        run: go test -v ./...

      - name: Build
        uses: wangyoucao577/go-release-action@v1.17
        env:
          CGO_ENABLED: 1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
          project_path: "."
          binary_name: "capclient"
          ldflags: "-s -w"
          extra_files: README.md
