on: [push, pull_request]
name: Test
jobs:
  build:
    name: Build and Test
    strategy:
      matrix:
        go-version: [1.16.x]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:

      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}

      - name: Checkout code
        uses: actions/checkout@v2

      - name:  Install Dependencies
        shell: bash
        run:   |
              if [ "$RUNNER_OS" == "Linux" ]; then
                    sudo apt install -y libgl1-mesa-dev xorg-dev libglfw3-dev
              fi

      - name: Test
        run: go test -v ./...

      - name: Build
        run: go build .

      - name: Release
        # uses: softprops/action-gh-release@v1
        uses: wangyoucao577/go-release-action@v1.19
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: capclient*
