on: [push, pull_request]
name: Test
jobs:
  build:
    name: Build and Test
    strategy:
      matrix:
        go-version: [1.17.x]
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:

      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}

      - name: Checkout code
        uses: actions/checkout@v2

      - name:  Install Dependencies
        shell: bash
        run:   |
              if [ "$RUNNER_OS" == "Linux" ]; then
                apt-get -qq -y install --no-install-recommends && apt install -y libgl1-mesa-dev xorg-dev libusb-dev libyubikey-dev libykpers-1-dev
              fi

      - name: Generate
        run: go generate ./...

      - name: Build
        run: go build .

      - name: Test
        run: go test -v ./...
